require: rubocop-rspec

AllCops:
  Exclude:
    - "vendor/**/*"
    - "db/**/*"
    - "tmp/**/*"
    - "bin/**/*"
    - "config/**/*"
    - "Gemfile"
  DisplayCopNames: true

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  Max: 160

RSpec/ContextWording:
  Enabled: false

RSpec/ExampleLength:
  Max: 10

RSpec/ImplicitSubject:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 5

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
